name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build for multiple platforms
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/tmuxcraft ./cmd/tmuxcraft/main.go
          GOOS=darwin GOARCH=amd64 go build -o dist/tmuxcraft ./cmd/tmuxcraft/main.go
          GOOS=darwin GOARCH=arm64 go build -o dist/tmuxcraft ./cmd/tmuxcraft/main.go
          GOOS=windows GOARCH=amd64 go build -o dist/tmuxcraft.exe ./cmd/tmuxcraft/main.go

      - name: Compress binaries
        run: |
          zip dist/tmuxcraft-linux-amd64.zip dist/tmuxcraft
          zip dist/tmuxcraft-darwin-amd64.zip dist/tmuxcraft
          zip dist/tmuxcraft-darwin-arm64.zip dist/tmuxcraft
          zip dist/tmuxcraft-windows-amd64.zip dist/tmuxcraft.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
